feature: tests for ios & android
evva-sfw/abrevva-react-native pull request #23
Opened 2024-08-14 08:51 UTC by mhochsto

2024-08-14 09:10 UTC, codepushr approved these changes

2024-08-14 09:28 UTC, axi92 commented
@mhochsto do you know how we could execute the swift tests via cli?
We already test the javascript context with `yarn test` and kotlin with the android build.
But iOS is not executed yet in the workflows.
Would be nice to have them executed as well.

2024-08-14 14:25 UTC, axi92 requested changes
TODO:
- [ ] swift test execution in workflow

2024-08-23 06:06 UTC, axi92 commented on .github/workflows/test.yml
>          run: xcrun --toolchain ${{ env.TOOLCHAINS }} swift --version
Is the toolchains env populated?
Maybe print it for debugging?

2024-08-23 11:53 UTC, codepushr approved these changes

2024-08-25 08:21 UTC, axi92 approved these changes

2024-08-26 07:21 UTC, codepushr approved these changes

2024-08-26 07:21 UTC, merged